<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kiwi_popup"
 *
 * Auto generated by Extension Builder 2016-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Kiwi Popup',
	'description' => 'Opens an image as popup when loading a page (once a session or on every page load)',
	'category' => 'plugin',
	'author' => 'Andreas Kiefer',
	'author_email' => 'kiefer@kiefer.koeln',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);